import { errorResponse } from "./response.js"

export enum ErrorCode {
  VALIDATION_ERROR = "VALIDATION_ERROR",
  AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR",
  AUTHORIZATION_ERROR = "AUTHORIZATION_ERROR",
  NOT_FOUND = "NOT_FOUND",
  CONFLICT = "CONFLICT",
  INTERNAL_ERROR = "INTERNAL_ERROR",
  RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",
  PAYMENT_TIMEOUT = "PAYMENT_TIMEOUT",
  PAYMENT_REJECTED = "PAYMENT_REJECTED",
  PAYMENT_NOT_FOUND = "PAYMENT_NOT_FOUND",
  INVALID_PAYMENT_STATUS = "INVALID_PAYMENT_STATUS",
  ORDER_NOT_FOUND = "ORDER_NOT_FOUND",
  PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND",
  PRODUCT_UNAVAILABLE = "PRODUCT_UNAVAILABLE",
  CATEGORY_NOT_FOUND = "CATEGORY_NOT_FOUND",
  DUPLICATE_CATEGORY_NAME = "DUPLICATE_CATEGORY_NAME",
  DUPLICATE_PRODUCT_SKU = "DUPLICATE_PRODUCT_SKU",
  INVALID_CATEGORY = "INVALID_CATEGORY",
  INVALID_PRODUCT_STATUS = "INVALID_PRODUCT_STATUS",
  INVALID_STATUS_TRANSITION = "INVALID_STATUS_TRANSITION",
  CART_EMPTY = "CART_EMPTY",
  CART_NOT_FOUND = "CART_NOT_FOUND",
  CART_ITEM_NOT_FOUND = "CART_ITEM_NOT_FOUND",
  INVALID_OPTION = "INVALID_OPTION",
  INACTIVE_OPTION = "INACTIVE_OPTION",
  REQUIRED_OPTION_MISSING = "REQUIRED_OPTION_MISSING",
  INVALID_QUANTITY = "INVALID_QUANTITY",
  MAX_QUANTITY_EXCEEDED = "MAX_QUANTITY_EXCEEDED",
  NOTIFICATION_NOT_FOUND = "NOTIFICATION_NOT_FOUND",
  NOTIFICATION_TEMPLATE_NOT_FOUND = "NOTIFICATION_TEMPLATE_NOT_FOUND",
  NOTIFICATION_ALREADY_READ = "NOTIFICATION_ALREADY_READ",
  INVALID_NOTIFICATION_TYPE = "INVALID_NOTIFICATION_TYPE",
  INVALID_NOTIFICATION_STATUS = "INVALID_NOTIFICATION_STATUS",
  NOTIFICATION_PREFERENCE_NOT_FOUND = "NOTIFICATION_PREFERENCE_NOT_FOUND",
  NOTIFICATION_RETRY_EXHAUSTED = "NOTIFICATION_RETRY_EXHAUSTED",
  SETTING_NOT_FOUND = "SETTING_NOT_FOUND",
  INVALID_SETTING_VALUE = "INVALID_SETTING_VALUE",
  SETTING_KEY_REQUIRED = "SETTING_KEY_REQUIRED",
  INVALID_FILE_TYPE = "INVALID_FILE_TYPE",
  FILE_TOO_LARGE = "FILE_TOO_LARGE",
  SETTING_DELETE_FORBIDDEN = "SETTING_DELETE_FORBIDDEN",
  // Staff domain
  STAFF_NOT_FOUND = "STAFF_NOT_FOUND",
  STAFF_ALREADY_EXISTS = "STAFF_ALREADY_EXISTS",
  STAFF_EMAIL_DUPLICATE = "STAFF_EMAIL_DUPLICATE",
  INVALID_STAFF_ROLE = "INVALID_STAFF_ROLE",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  STAFF_INACTIVE = "STAFF_INACTIVE",
  STAFF_DISABLED = "STAFF_DISABLED",
  CANNOT_MODIFY_SELF = "CANNOT_MODIFY_SELF",
  INSUFFICIENT_PRIVILEGE = "INSUFFICIENT_PRIVILEGE",
  INVALID_STAFF_TOKEN = "INVALID_STAFF_TOKEN",
  STAFF_TOKEN_EXPIRED = "STAFF_TOKEN_EXPIRED",
}

export class AppError extends Error {
  constructor(
    public readonly statusCode: number,
    public readonly code: ErrorCode,
    message: string,
  ) {
    super(message)
    this.name = "AppError"
  }

  serialize() {
    return errorResponse(this.code, this.message)
  }
}

export function notFound(message: string, code = ErrorCode.NOT_FOUND) {
  throw new AppError(404, code, message)
}

export function badRequest(
  message: string,
  code = ErrorCode.VALIDATION_ERROR,
) {
  throw new AppError(400, code, message)
}

export function unauthorized(
  message = "Unauthorized",
  code = ErrorCode.AUTHENTICATION_ERROR,
) {
  throw new AppError(401, code, message)
}

export function forbidden(
  message = "Forbidden",
  code = ErrorCode.AUTHORIZATION_ERROR,
) {
  throw new AppError(403, code, message)
}

export function conflict(message: string, code = ErrorCode.CONFLICT) {
  throw new AppError(409, code, message)
}
